### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by Eirtrand** [WillBrennan/ImageStitching#1]
In the makefile pip tries to find requirements.txt, can you include it to the project or am I missing something?

**Comment by WillBrennan** [comment]
Hey - Nice catch, thankyou! 

You're not missing anything, I forgot to include one. I've just added a requirements.txt with numpy in it. ImageStitching also needs opencv which can't be installed through pip (please correct me if I'm wrong!). 

You can install opencv with brew or apt-get.

```
brew install opencv3 --with-contrib --with-python3
```

```
sudo apt-get install libopencv-dev python-opencv
```

**Comment by huadee** [comment]
Does this only use for opencv3?

**Comment by WillBrennan** [comment]
It should support both opencv2 and opencv3. For opencv3 it will require the contributions module so that SIFT features can be computed.
