### ISSUE TITLE
Mosaic or the panaroma gets blurred

### ISSUE THREAD

**Issue by shubham-shahh** [WillBrennan/ImageStitching#12]
Hi, when I am stitching the video, the output image has blurred the initial part of the image, how can I go
![resulted1](https://user-images.githubusercontent.com/51359628/123736565-f6be8900-d8be-11eb-888e-059cade0b829.png)
 about solving this issue? as you can see the bottom of the image is blurred
Here's an example image

**Comment by WillBrennan** [comment]
Hi; you've likely got heavy radial distortion in the camera which this library doesn't handle. This isn't handled at the moment and isn't trivial to add. Do you have a the original images you passed into this?

**Comment by shubham-shahh** [comment]
Hi, [this](https://www.pexels.com/video/video-of-car-travelling-1394254/) is the original video I tried with the video_stitching.py

**Comment by WillBrennan** [comment]
There's a lot of radial distortion in this video, you can see the trees on the left and right side of the images bend a long way away from the camera. This method will struggle to deal with it as it doesn't handle radial distortion as its using normal OpenCV functions.

**Comment by shubham-shahh** [comment]
Can I apply some correction method from the source

**Comment by WillBrennan** [comment]
Yes, you can try undistorting it before hand with opencv, and then run it through this. There should be examples of how to do this with a quick google.
