### ISSUE TITLE
device freezes while processing the video

### ISSUE THREAD

**Issue by shubham-shahh** [WillBrennan/ImageStitching#14]
Hi, I am using video_stitching.py, after a certain amount of frames my device freezes, I don't think it is because of hardware limitations as my ram and CPU both don't even reach 50% of load.

**Comment by WillBrennan** [comment]
Hi; 

Its not where the application is freezing, its where the application is calculating SIFT features, its a slow algorithm and I believe the OpenCV implementation is single threaded. You could look at making an option to change between SIFT and something like SURF or ORB that are quicker but less reliable?

**Comment by shubham-shahh** [comment]
Okay, will try that. thanks

**Comment by shubham-shahh** [comment]
Hi, I tried using surf, but still, I faced the same problem.
