### ISSUE TITLE
Program not running

### ISSUE THREAD

**Issue by joel-Y** [WillBrennan/ImageStitching#15]
Hey Will,

I tried to run the program by following your instructions, but there is no make file and I did output only one image when doing videos.

Can you please help?

Thanks,

**Comment by WillBrennan** [comment]
Hey! Sorry, the Makefile got removed in a refactor a few months ago, it was only used to install dependencies. The readme is up to date now. 

If you clone the repo, make sure you've got opencv + numpy installed, you can then just navigate to the base directory of this project and run the script, 


```
git clone https://github.com/WillBrennan/ImageStitching
cd ImageStitching
pip install -r requirements.txt 
python stitching.py ~/Pictures/my_videos/
```

. This script is expected to only output one image as its stitching the frames from the video or images together into a single mosaic. There's an example of a stitched image in the readme.

**Comment by joel-Y** [comment]
Hey Will,

Oh okay, I thought it'd output a stitched panoramic video.

Thanks,
