### ISSUE TITLE
Stitching creates blur on invisible parts

### ISSUE THREAD

**Issue by PlugNPush** [WillBrennan/ImageStitching#20]
Hi Will, I am doing some testing with your project for a school project. You probably stopped developing it, but I was wondering if you could give me a clue about why the invisible images get blurred the more the process continues, and how it could be fixed if you know?

Attached is a picture of Frame 935 (example), that illustrates the issue:
![result_935](https://user-images.githubusercontent.com/31410359/232028721-aeff0868-cd42-47c7-9ec8-c5ea7369c81b.jpg)

**Comment by WillBrennan** [comment]
Hey! 

This project doesn't account for radial distortion from the camera. When you stitch a lot of frames together it causes this blurring pattern. 

You can either remove radial distortion before you process the images or use less images. I hope that helps!
