### ISSUE TITLE
there's a problem when stitching more than 34 images

### ISSUE THREAD

**Issue by MugleLei** [WillBrennan/ImageStitching#5]
video_stitching has a bug:
Traceback (most recent call last):
  File "video_stitching.py", line 46, in <module>
    cap = cv2.VideoCapture(args.video_path)
TypeError: an integer is required

so I use image_stitching to stitch images captured from video, but I can't stitch 35 images at a time while stitch 34 images are fine. Also when stitching 80 images, No.1-34 disappear and No.35-80 are fine.
I run the program in both opencv2.4 and opencv3.2 and they have the same problem. Is there any limitation in the code? I'm not familiar with opencv so I can't find the limitation myself.

when stitching 34 images:
![stitched_34](https://user-images.githubusercontent.com/30332538/31810865-ec3b569c-b5af-11e7-83e2-c1c839e61dc2.png)

when stitching 35 images:
![stitched_35](https://user-images.githubusercontent.com/30332538/31810874-f5620068-b5af-11e7-873d-7aaa852c36b6.png)

when stitching 36 images:
![stitched_36](https://user-images.githubusercontent.com/30332538/31812038-4998ba4c-b5b4-11e7-8bb9-86372af3d9c0.png)

when stitching 80 images:
![stitched_80](https://user-images.githubusercontent.com/30332538/31812063-5ed1d5c4-b5b4-11e7-9a80-ff8be8dfb44f.png)

**Comment by WillBrennan** [comment]
This method isn't taking into account lens distortion when stitching the images. This is okay on mobile phone footage, but it looks like you're using a lens with distortion.

Usually you have to undistort the images and stitch them.
