### ISSUE TITLE
Reference link is dead

### ISSUE THREAD

**Issue by SSBakh** [WillBrennan/ImageStitching#6]
What it says on the tin. I googled the title and my best guess was this:
Springer: https://link.springer.com/article/10.1007/s11263-006-0002-3
ResearchGate: https://www.researchgate.net/publication/225133245_Automatic_Panoramic_Image_Stitching_using_Invariant_Features
There's an ACM link on google I think, but it's not really working for me (due to some reason unbeknownst to me), but I think this should suffice.
Should I put in a pull request?

**Comment by WillBrennan** [comment]
Hi there - A PR would be great.
