### ISSUE TITLE
error when running program

### ISSUE THREAD

**Issue by akshayacharya97** [WillBrennan/ImageStitching#7]
When i execute the video stitch program from termincal , the following error comes. Wha should I do?

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "image_stitching.py", line 12, in <module>
    import image_stitching
  File "/home/akshay/VideoStitcher/image_stitching/__init__.py", line 5, in <module>
    from matching import *
AttributeError: module 'matching' has no attribute 'Matching'

**Comment by WillBrennan** [comment]
Hi;

It looks like this is where the project was written for python 2 instead of python 3, the import syntax is now, 

```python
from .matching import * 
```
. It should be a really simple change and it'd be much appreciated if you could make a PR?

**Comment by akshayacharya97** [comment]
Hello,
I have a question. I want to create a panorama from around 30 to 40 images obtained from frames of a video. The video is obtained by linearly moving and capturing the subject. The frames are pretty close and has a good overlap. Now what is the best way to create a long panorama of this?
