### ISSUE TITLE
Python is crashing suddenly

### ISSUE THREAD

**Issue by akshayacharya97** [WillBrennan/ImageStitching#9]
I have attached the screenshot of the error. The images are loading from the folder but then soemting is happening right after and the program is crashing.

This is the error

zsh: segmentation fault  python3 image_stitching.py --save --quiet

![Screen Shot 2021-01-19 at 15 35 09](https://user-images.githubusercontent.com/61483737/105002236-47aa9580-5a74-11eb-9f3a-1c1d25e8b71d.png)

**Comment by WillBrennan** [comment]
This has been fixed with #13
